<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "annuaire_hv"
 *
 * Auto generated by Extension Builder 2017-06-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Annuaire HV',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Hugo Uranga, Vincent Ventura',
	'author_email' => 'uranga.hugo@orange.fr, vincent.ventura1@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);